#!/usr/bin/env python3
"""
Build Bronze manifest for API v1 endpoint.
Tries multiple sources in order:
1. Root manifest.json (generated by manifest_generator.py)
2. website/data/filings.json (legacy)
3. Creates minimal placeholder if neither exists
"""
import boto3
import json
from datetime import datetime

S3_BUCKET = "congress-disclosures-standardized"
DEST_KEY = "website/api/v1/documents/manifest.json"

# Try these sources in order
SOURCE_KEYS = [
    "manifest.json",  # Root manifest (preferred)
    "website/data/filings.json",  # Legacy location
]

def create_placeholder_manifest():
    """Create a minimal placeholder manifest if no source data exists."""
    return {
        "stats": {
            "total_filings": 0,
            "total_members": 0,
            "latest_year": None,
            "last_updated": datetime.utcnow().strftime("%Y-%m-%d")
        },
        "filings": []
    }

def main():
    s3 = boto3.client("s3", region_name="us-east-1")
    
    manifest = None
    source_used = None
    
    # Try each source in order
    for source_key in SOURCE_KEYS:
        try:
            print(f"📥 Trying source: {source_key}...")
            response = s3.get_object(Bucket=S3_BUCKET, Key=source_key)
            data = json.loads(response["Body"].read().decode("utf-8"))
            
            # Reformat to match API v1 structure
            # Reformat to match API v1 structure
            filings = data.get("filings", [])
            
            # Recalculate stats to ensure accuracy
            unique_members = set()
            for f in filings:
                # Create unique member key from name
                member_key = f"{f.get('last_name', '')}|{f.get('first_name', '')}"
                unique_members.add(member_key)
            
            stats = data.get("stats", {})
            stats['total_filings'] = len(filings)
            stats['total_members'] = len(unique_members)
            
            manifest = {
                "stats": stats,
                "filings": filings
            }
            source_used = source_key
            print(f"✅ Loaded from {source_key}: {len(manifest.get('filings', []))} filings")
            break
            
        except s3.exceptions.NoSuchKey:
            print(f"  ⚠️  {source_key} not found, trying next source...")
            continue
        except Exception as e:
            print(f"  ⚠️  Error reading {source_key}: {e}, trying next source...")
            continue
    
    # If no source found, create placeholder
    if manifest is None:
        print("⚠️  No source manifest found, creating placeholder...")
        manifest = create_placeholder_manifest()
        source_used = "placeholder"
    
    # Upload to API endpoint
    print(f"📤 Uploading to {DEST_KEY}...")
    s3.put_object(
        Bucket=S3_BUCKET,
        Key=DEST_KEY,
        Body=json.dumps(manifest, indent=2),
        ContentType="application/json",
        CacheControl="max-age=300"
    )
    
    print(f"✅ Bronze manifest created at API endpoint (source: {source_used})")
    print(f"📍 URL: https://{S3_BUCKET}.s3.us-east-1.amazonaws.com/{DEST_KEY}")
    print(f"📊 Stats: {manifest['stats']}")

if __name__ == "__main__":
    main()
